version: '2'
services:

  master:
    container_name: master_wordpress
    environment:
      VIRTUAL_HOST: 'local.master.jc'
    volumes:
      - ./app/:/apps/backend/:rw
    ports:
      - 80:80
networks:
  default:
    external:
      name: juan_network
